# Generated by Django 6.0.1 on 2026-02-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_weeklyplan_weeklyplanversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyplan',
            options={'ordering': ['-week_start']},
        ),
    ]
